
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    password: root
    username: root
  messages:
    basename: i18n/index


#  devtools:
#    restart:
#      # 热部署开关，false即不启用热部署
#      enabled: false
#      # 指定热部署的目录
#      additional-paths: src/main/java
#      # 指定目录不更新
#      #exclude: test/**

#application:
#  name: staging
server:
  port: 8080



# 配置对象
yaml-object:
  name: gbs${random.uuid}
  #name: gbs${random.int}
  age: 22
  happy: true
  birth: 1998-08-25
  email: sss@foxmail.com
  maps: {k1: v1,k2: v2}
  #  lists:
  #    - code
  #    - music
  #    - girl
  lists: [code,music,girl]
  dog:
    # 如果yaml-object.name1 不存在则取后面的值
    name: ${yaml-object.name1:dognameisnull}
    age: 3



#查看哪些自动配置生效了哪些没生效
#Positive matches:表示生效
#Negative matches: 没生效
#Unconditional classes: 不满足条件的
debug: true
